### PR TITLE
Made the site responsive for users

### PR DESCRIPTION
**Pull request by Karan-Palan**
Made the site responsive for various type of devices by adding another css file, using media query and linking it to HTML.
You can checkout the changes here:
Before:

https://github.com/surjendu104/CODEy/assets/143683619/4ea36507-3406-45bb-9787-881b188219f6

After:

https://github.com/surjendu104/CODEy/assets/143683619/db694601-1167-4c6f-b930-e255767e55ae

Task done:
- [x] Make the site responsive

### CODE REVIEW

**Comment by surjendu104** [comment]
@Karan-Palan Thanks for your contribution 🎉🎉

**Review by surjendu104 — APPROVED** [review]

**Comment by Karan-Palan** [comment]
Thanks, would love to contribute more!

**Comment by Karan-Palan** [comment]
I could improve the buttons by adding a hover effect

**Comment by surjendu104** [comment]
> I could improve the buttons by adding a hover effect

yeah sure. you can also change the media.css for the support in mobile phones. use the responsive tab to see the responsiveness

**Pull request merged**
